//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Data_r0704742Entities : DbContext
    {
        public Data_r0704742Entities()
            : base("name=Data_r0704742Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aankoop> Aankoop { get; set; }
        public virtual DbSet<Champion> Champions { get; set; }
        public virtual DbSet<Friendship> Friendship { get; set; }
        public virtual DbSet<Gamemode> Gamemode { get; set; }
        public virtual DbSet<Icon> Icons { get; set; }
        public virtual DbSet<Matchhistory> Matchhistory { get; set; }
        public virtual DbSet<Prijs> Prijs { get; set; }
        public virtual DbSet<Profiel> Profiel { get; set; }
        public virtual DbSet<Skin> Skins { get; set; }
        public virtual DbSet<Speler> Speler { get; set; }
        public virtual DbSet<Spelers_champion> Spelers_champions { get; set; }
        public virtual DbSet<Spelers_Icon> Spelers_Icons { get; set; }
        public virtual DbSet<Spelers_Skin> Spelers_Skins { get; set; }
        public virtual DbSet<Spelersaccount> Spelersaccount { get; set; }
        public virtual DbSet<Store> Store { get; set; }
    }
}
