//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfLegends_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matchhistory
    {
        public int id { get; set; }
        public System.DateTime Datum { get; set; }
        public int Kills { get; set; }
        public int Death { get; set; }
        public int Assist { get; set; }
        public string Itemset { get; set; }
        public int gamemodeId { get; set; }
    
        public virtual Gamemode Gamemode { get; set; }
    }
}
